# -*- coding: utf-8 -*-
# :Project:   python-rapidjson -- Configuration to build and upload manylinux1 wheels to PyPI
# :Author:    Lele Gaifax <lele@metapensiero.it>
# :License:   MIT License
# :Copyright: © 2017 Lele Gaifax
#

# Note that due to a strange issue with Travis CI, the Python 3.6 wheels are
# actually built via Gitlab CI, on the repository
# https://gitlab.com/metapensiero/python-rapidjson.
#
# Here we execute the Python 3.6 tests; Python 3.4 and 3.5 tests are run by
# cibuildwheel, inside the manylinux1 Docker image.

# We also run tests for memory leaks (which require a debug build of python)
# using python3.4. Specifically we install python3.4-dbg, the only python3
# runtime with debug support present on the travis-ci platform at the moment.
#
# See https://mail.python.org/pipermail/wheel-builders/2017-August/000285.html
---
language: python
os: osx
python:
  - "3.4"
  - "3.5"
  - "3.6"
osx_image:
  - xcode9

env:
  global:
    - CIBW_TEST_REQUIRES="pytest pytest-benchmark pytz"
    - CIBW_TEST_COMMAND="py.test {project}/tests"
    - CIBW_SKIP="cp2* cp33* cp36-manylinux1*"
    - TWINE_USERNAME=lelit
      # Note: TWINE_PASSWORD is set in Travis settings

install:
  - |
    if [ $RUN_DEBUG_PYTHON = true ]; then
      sudo apt-get install python3.4-dbg
      virtualenv -p python3.4-dbg /tmp/env
      . /tmp/env/bin/activate
    fi
  - pip3 install -r requirements-test.txt

script:
  - pip3 install .
  - pytest tests
  - pushd docs
  - make doctest -e PYTHON=$(which python3)
  - popd
  - |
    pip3 install cibuildwheel==0.6.0
    cibuildwheel --output-dir wheelhouse
    if [[ $TRAVIS_TAG ]]; then
      pip3 install twine
      python3 -m twine upload wheelhouse/*.whl
    fi
